# Generated by Django 2.0 on 2019-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20190206_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
