# Generated by Django 2.2.2 on 2019-06-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_profesional_apellido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesional',
        ),
    ]
